option for secondary baseline
epiforecasts/EpiNow2 pull request #288
Opened 2022-02-01 19:46 UTC by sbfnk

Adds a baseline level to the secondary model, i.e. a constant component that is not affected by the primary data stream (somewhat akin to the endemic component in `hhh4`. This was motivated by observations that the model currently seems quite a long way off the data in some countries (though not all) in the European Forecast Hub submissions. When inspecting some of the raw data on cases and admissions, the relationship seemed reasonably close to linear but with an intercept at >0. 

Visually, the updated model connects somewhat better to recent data (if not impressively so, possibly because still fitting to a mixture of Delta and Omicron), but it comes at the expense of less straightforward epidemiological interpretation of the estimated delay and scaling - happy to hear of other suggestions that could improve things.

From https://github.com/sophiemeakin/ecdc-covid19-admissions/blob/main/main.R

Without baseline:
<img width="1480" alt="image" src="https://user-images.githubusercontent.com/1156307/152038437-e1ec5ed6-c1ab-4b5c-a89c-12179fa0af3f.png">

With baseline:
<img width="1487" alt="image" src="https://user-images.githubusercontent.com/1156307/152039234-0605e987-ea8c-45f3-bf4b-5d79e792fb61.png">

2022-02-01 19:46 UTC, sbfnk commented
Tagging @sophiemeakin

2022-02-02 08:33 UTC, sophiemeakin commented
This seems like a good temporary fix and the code changes seem fine - but I wonder why this is happening? Some thoughts:
My first q would be is the misalignment between observed and forecast admissions due to the fit of the secondary model, or the case forecasts? 
If the former - do we have an idea why is this happening, and so whether it's a temporary or permanent issue? If it's only a temporary change (e.g. change in variant distributions, reporting etc. etc.), then we should look at how adding the baseline will affect other locations where this temporary change isn't present (e.g. the UK forecast looks better without the baseline than with it).
If the latter (although I suspect it isn't as we are using the hub-ensemble case forecast), then I personally wouldn't include the baseline in the model - the issue is with the case forecasts and we should think about how we can correct those instead.

2022-02-02 11:00 UTC, sbfnk commented
> This seems like a good temporary fix and the code changes seem fine - but I wonder why this is happening? Some thoughts: My first q would be is the misalignment between observed and forecast admissions due to the fit of the secondary model, or the case forecasts? If the former - do we have an idea why is this happening, and so whether it's a temporary or permanent issue?

The fits of the secondary model to past data look poor so I think it's a combination of data and variants that break the underlying assumption of linear scaling over a 12-week period, even before case forecasts come in to complicate things further.

As an illustration, here's cases and 1-week shifted admissions, and a linear fit with setting intercept at 0 vs. leaving it free.

<img width="1484" alt="image" src="https://user-images.githubusercontent.com/1156307/152141309-8261030f-cf2b-4e96-86b4-c3f89cf698d1.png">

2022-02-03 13:26 UTC, seabbs requested changes
Interesting stuff.

 I think having this as a component of the model makes sense (with thinking about moving towards a renewal + convolution of upstream + endemic being a place to target). Not sure it is exactly the resolution to the current problem which I thought was more driven by rapid changes in the CFR, CHR etc due to Omicron replacing Delta and large scale boosting (we saw this early last year when vaccination was rolling out but it was less obvious as most places where on the downslope). Having it be turned of by default seems like a good call but I think exposing and documenting to the user would be a good idea. 

We obviously looked at having that CHR being time-varying and it became quite involved as a project (#261). A simplified solution using a random walk on the scaling parameter might help quite a bit? 

In terms of this PR. I think probably need the following: 

- [ ] Expose setting to the user
- [ ] Document
- [ ] Expose prior setting to the user (optional)
- [ ] Add news update 
- [ ] Add version bump
- [ ] Test addition (optional).

2022-02-03 13:26 UTC, seabbs commented on inst/stan/estimate_secondary.stan
> +    secondary_baseline[1] ~ normal(0, min(obs)) T[0, ];
better to set min(obs) in transformed data.

2022-02-03 13:26 UTC, seabbs commented on inst/stan/estimate_secondary.stan
> +    secondary_baseline[1] ~ normal(0, min(obs)) T[0, ];
or better yet in R

2022-02-03 13:26 UTC, seabbs commented on R/estimate_secondary.R
> +      estimate_baseline = 0
user control to turn this on or off independently? Could think about doing so by passing the mean intercept and having 0 be the setting that turns it off (so endemic = c(100, 10) is a prior of N(100, 10), and endemic = 0 turns it off)

2022-02-03 13:26 UTC, seabbs commented on R/estimate_secondary.R
> +      estimate_baseline = 0
better to add this to the list outside of the if-else step to avoid duplication.

2022-08-31 09:37 UTC, seabbs commented
Are you still interested in having this merged?

2022-08-31 09:43 UTC, sbfnk commented
Possibly but it needs to be revisited and your bullet points addressed. I've converted it to a draft for now.

2023-04-28 11:24 UTC, sbfnk commented
I'm not convinced this is still needed. Closing for now.

2023-04-28 11:24 UTC, closed without merging