Revise the examples for `create_backcalc_data()`
epiforecasts/EpiNow2 pull request #388
Opened 2023-05-11 14:44 UTC by jamesmbaazam

This PR revises the previous example in `create_backcalc_data()` because it was calling `create_gp_data()` instead of `create_backcalc_data()`. 

This PR closes #385

2023-05-18 21:25 UTC, seabbs requested changes
Thanks James - good to have this fixed. 

Could you 

- [x] rebase on main
- [ ] update the docs
- [ ] update the Dev version
- [ ] add a news item

Then good to go.

2023-05-22 10:12 UTC, jamesmbaazam commented
Thanks, Sam. I believe this is ready to be merged.

2023-05-22 10:51 UTC, seabbs requested changes
A few more slight niggles

2023-05-22 10:51 UTC, seabbs commented on NEWS.md
> +  instead of `create_gp_data()`. By @jamesmbaazam in #388 and review by @seabbs.
review -> reviewed

2023-05-22 10:51 UTC, seabbs requested changes
A few more slight niggles

2023-05-22 11:11 UTC, jamesmbaazam commented on NEWS.md
> +# EpiNow2 1.3.6.3000
Oops! I'll remove it.

2023-05-22 11:11 UTC, jamesmbaazam commented on NEWS.md
> +  instead of `create_gp_data()`. By @jamesmbaazam in #388 and review by @seabbs.
Great. Thanks.

2023-05-22 13:54 UTC, seabbs approved these changes
LGTM - thanks James. Note I went in an incremented the dev version.

2023-05-22 13:54 UTC, merged