Move secondary_opts to opts.R
epiforecasts/EpiNow2 pull request #570
Opened 2024-02-21 16:11 UTC by jamesmbaazam

## Description

This PR closes #493.

The `secondary_opts()` function was previously defined in the `estimate_secondary.R` script. It has now been moved to the `opts.R` script where all other `_opts*()` related functions live. This will make it easier to find.

## Initial submission checklist

- [x] My PR is based on a package issue and I have explicitly linked it.
- [x] I have tested my changes locally (using `devtools::test()` and `devtools::check()`).
- [ ] I have added or updated unit tests where necessary.
- [ ] I have updated the documentation if required and rebuilt docs if yes (using `devtools::document()`).
- [x] I have followed the established coding standards (and checked using `lintr::lint_package()`).
- [ ] I have added a news item linked to this PR.

## After the initial Pull Request 

- [ ] I have reviewed Checks for this PR and addressed any issues as far as I am able.

2024-02-22 08:13 UTC, sbfnk requested changes
Thanks! Can we move the function down e.g. to after `generation_time_opts()` as the `estimate_infections` model is the "primary" one so should come first?

2024-02-22 11:20 UTC, jamesmbaazam commented
> Thanks! Can we move the function down e.g. to after `generation_time_opts()` as the `estimate_infections` model is the "primary" one so should come first?

Done!

2024-02-22 13:02 UTC, sbfnk submitted a review, later dismissed

2024-02-23 08:24 UTC, sbfnk approved these changes

2024-02-26 07:49 UTC, merged