add forecast_opts()
epiforecasts/EpiNow2 pull request #901
Opened 2024-12-17 16:46 UTC by sbfnk

## Description

This PR closes #867 and part of #898 whilst enabling addressing #640.

It introduces a `forecast` argument to `estimate_infections()` that is set via `forecast_opts()` (preferred over `add_horizon()` as it allows us to identify the last date in the data - though the `add_horizon()` function exists internally so we could make the switch at a later time if we want).

## Initial submission checklist

- [X] My PR is based on a package issue and I have explicitly linked it.
- [X] I have tested my changes locally (using `devtools::test()` and `devtools::check()`).
- [X] I have added or updated unit tests where necessary.
- [X] I have updated the documentation if required and rebuilt docs if yes (using `devtools::document()`).
- [X] I have followed the established coding standards (and checked using `lintr::lint_package()`).
- [X] I have added a news item linked to this PR.

## After the initial Pull Request 

- [ ] I have reviewed Checks for this PR and addressed any issues as far as I am able.

2024-12-18 14:20 UTC, jamesmbaazam requested changes
Thanks for implementing this, Seb.

I made a few comments and suggestions.

2024-12-18 15:36 UTC, sbfnk reviewed
Thanks, @jamesmbaazam. Did the new identification of gaps look OK to you (I think you weren't convinced of the idea in the corresponding Issue)? https://github.com/epiforecasts/EpiNow2/blob/8003d06fda877745f7242e09e0355533f1d3bb97/R/create.R#L447

2024-12-18 15:36 UTC, sbfnk commented on R/create.R
> +  imputed_time <- cases[!(accumulate), lookup]
I agree but - should we then also rename `cases_time` to `case_times`?

2024-12-18 15:36 UTC, sbfnk commented on R/create.R
> +    estimate_early_dynamics(confirmed_cases, seeding_time)
Sorry, I shifted things around a bit. Before we had

```r
  cases <- data[(seeding_time + 1):(.N - horizon)]
  cases <- cases$confirm
```

and now we have

```r
  cases <- data[(seeding_time + 1):.N]
  confirmed_cases <- cases[1:(.N - forecast$horizon)]$confirm
```

So I think what was `cases` before is the same as what is `confirmed_cases` now.

2024-12-18 15:36 UTC, sbfnk commented on R/opts.R
> +#' @description `r lifecycle::badge("stable")`
Probably not, will change.

2024-12-18 15:36 UTC, sbfnk commented on R/opts.R
> +#' rstan functions.
yep

2024-12-18 15:36 UTC, sbfnk commented on tests/testthat/test-gp_opts.R
> -test_that("gp_opts returns correct default values", {
yes, will revert.

2024-12-18 15:48 UTC, jamesmbaazam commented
> I agree but - should we then also rename cases_time to case_times? 

That would be better too.

2024-12-19 15:50 UTC, jamesmbaazam commented on R/create.R
> +    estimate_early_dynamics(confirmed_cases, seeding_time)
I see now. Thanks.

2024-12-19 16:05 UTC, sbfnk commented on R/create.R
> +  imputed_time <- cases[!(accumulate), lookup]
https://github.com/epiforecasts/EpiNow2/pull/901/commits/e6cdb09ece341736258cad45608efed14af58ce8 and  https://github.com/epiforecasts/EpiNow2/pull/901/commits/8302c5cf7e26712f4850c2b65f88d0933c1f33c8

2024-12-19 16:05 UTC, sbfnk commented on tests/testthat/test-gp_opts.R
> -test_that("gp_opts returns correct default values", {
[`d9c1430` (#901)](https://github.com/epiforecasts/EpiNow2/pull/901/commits/d9c14302f51fa75f98c03d3ed7f5ee0d11c98852)

2024-12-20 14:37 UTC, jamesmbaazam commented on R/opts.R
> +#' @description `r lifecycle::badge("stable")`
Okay, that clarifies it. Thanks.

2024-12-20 20:39 UTC, jamesmbaazam approved these changes

2024-12-20 21:28 UTC, merged